### ISSUE TITLE
RuntimeError: Deployment aws not supported!

### ISSUE THREAD

**Issue by jchigu** [spcl/serverless-benchmarks#125]
(python-venv) jchigu@SeBS:~/serverless-benchmarks$ docker ps -a
CONTAINER ID   IMAGE                                                  COMMAND                  CREATED         STATUS                     PORTS     NAMES
1b7bd595216e   spcleth/serverless-benchmarks:build.local.python.3.7   "/sebs/entrypoint.sh…"   2 minutes ago   Exited (1) 2 minutes ago             affectionate_morse
dfcd8badf210   spcleth/serverless-benchmarks:run.local.python.3.7     "/sebs/entrypoint.sh…"   10 hours ago    Up 10 hours                          heuristic_khayyam
b6adc3501159   spcleth/serverless-benchmarks:run.local.python.3.7     "/sebs/entrypoint.sh…"   13 hours ago    Up 13 hours                          youthful_khorana
9a6bb039cb76   spcleth/serverless-benchmarks:run.local.python.3.7     "/sebs/entrypoint.sh…"   13 hours ago    Up 13 hours                          youthful_heisenberg
0fa185899ccb   spcleth/serverless-benchmarks:build.local.python.3.7   "/sebs/entrypoint.sh…"   15 hours ago    Exited (1) 15 hours ago              nervous_banzai
06db4ceb8819   spcleth/serverless-benchmarks:build.local.python.3.7   "/sebs/entrypoint.sh…"   21 hours ago    Exited (0) 21 hours ago              modest_agnesi
a207caedcc94   hello-world                                            "/hello"                 27 hours ago    Exited (0) 27 hours ago              wizardly_chaplygin
(python-venv) jchigu@SeBS:~/serverless-benchmarks$ ./sebs.py benchmark invoke 110.dynamic-html test --config config/example.json --deployment aws --verbose
12:15:44,848 INFO SeBS-86aa: Created experiment output at /home/jchigu/serverless-benchmarks
ERROR:root:Deployment aws not supported!
Traceback (most recent call last):
  File "/home/jchigu/serverless-benchmarks/./sebs.py", line 32, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/jchigu/serverless-benchmarks/./sebs.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/home/jchigu/serverless-benchmarks/./sebs.py", line 99, in wrapper
    return func(*args, **kwargs)
  File "/home/jchigu/serverless-benchmarks/./sebs.py", line 217, in invoke
    ) = parse_common_params(**kwargs)
  File "/home/jchigu/serverless-benchmarks/./sebs.py", line 137, in parse_common_params
    deployment_client = sebs_client.get_deployment(
  File "/home/jchigu/serverless-benchmarks/sebs/sebs.py", line 106, in get_deployment
    raise RuntimeError("Deployment {name} not supported!".format(name=name))
RuntimeError: Deployment aws not supported!

===================================addition ======================================
(python-venv) jchigu@SeBS:~/serverless-benchmarks$ ./sebs.py benchmark regression test --config config/example.json --deployment aws --benchmark-name 120.uploader
Skip test test_110.dynamic-html
Select test test_120.uploader
Skip test test_210.thumbnailer
Skip test test_220.video-processing
Skip test test_311.compression
Skip test test_411.image-recognition
Skip test test_501.graph-pagerank
Skip test test_502.graph-mst
Skip test test_503.graph-bfs
Skip test test_504.dna-visualisation

-------------

sebs.regression.AWSTestSequence.test_120.uploader: fail
sebs.regression.AWSTestSequence.test_120.uploader: Traceback (most recent call last):
  File "/home/jchigu/serverless-benchmarks/sebs/regression.py", line 38, in test
    deployment_client = self.get_deployment(benchmark_name)
  File "/home/jchigu/serverless-benchmarks/sebs/regression.py", line 103, in get_deployment
    deployment_client = self.client.get_deployment(
  File "/home/jchigu/serverless-benchmarks/sebs/sebs.py", line 106, in get_deployment
    raise RuntimeError("Deployment {name} not supported!".format(name=name))
RuntimeError: Deployment aws not supported!

-------------

Succesfully executed 0 out of 1 functions
Failures when executing 1 out of 1 functions
- 120.uploader
===================================EXPERIMENT ERRORS========================================
(python-venv) jchigu@SeBS:~/serverless-benchmarks$ ./sebs.py experiment invoke perf-cost --config config/example.json --deployment aws
ERROR:root:Deployment aws not supported!
Traceback (most recent call last):
  File "/home/jchigu/serverless-benchmarks/./sebs.py", line 32, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/jchigu/serverless-benchmarks/./sebs.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/home/jchigu/serverless-benchmarks/./sebs.py", line 99, in wrapper
    return func(*args, **kwargs)
  File "/home/jchigu/serverless-benchmarks/./sebs.py", line 513, in experiment_invoke
    ) = parse_common_params(**kwargs)
  File "/home/jchigu/serverless-benchmarks/./sebs.py", line 137, in parse_common_params
    deployment_client = sebs_client.get_deployment(
  File "/home/jchigu/serverless-benchmarks/sebs/sebs.py", line 106, in get_deployment
    raise RuntimeError("Deployment {name} not supported!".format(name=name))
RuntimeError: Deployment aws not supported!
(python-venv) jchigu@SeBS:~/serverless-benchmarks$

**Comment by mcopik** [comment]
@jchigu Your error indicates that SeBS has been installed without all necessary dependencies. Please run `install.py` again, with flags for enabling AWS support - see docs for the example.

**Comment by mcopik** [comment]
Closing down - if the issue still persists, then please reopen with updated information instead of opening new ones.
