### ISSUE TITLE
botocore.exceptions.ConnectionClosedError:

### ISSUE THREAD

**Issue by jchigu** [spcl/serverless-benchmarks#129]
(python-venv) justinchigu@SeBSVM:~/serverless-benchmarks$ ./sebs.py benchmark invoke 220.video-processing test --config config/example.json --deployment aws --verbose
01:36:27,423 INFO SeBS-b157: Created experiment output at /home/justinchigu/serverless-benchmarks
01:36:27,956 INFO AWS.Credentials-4381: Using cached credentials for AWS
01:36:27,956 INFO AWS.Resources-5844: Using cached resources for AWS
01:36:27,956 INFO AWS.Config-7812: Using cached config for AWS
01:36:28,508 INFO Benchmark-da86: Using cached benchmark 220.video-processing at /home/justinchigu/serverless-benchmarks/cache/220.video-processing/aws/python/3.7/220.video-processing.zip
01:36:28,508 INFO AWS-f274: Creating new function! Reason: function 220_video_processing_python_3_7 not found in cache.
01:36:29,655 INFO AWS-f274: Creating function 220_video_processing_python_3_7 from /home/justinchigu/serverless-benchmarks/cache/220.video-processing/aws/python/3.7/220.video-processing.zip
ERROR:root:Connection was closed before we received a valid response from endpoint URL: "https://lambda.us-east-1.amazonaws.com/2015-03-31/functions".
Traceback (most recent call last):
  File "/home/justinchigu/serverless-benchmarks/sebs/aws/aws.py", line 176, in create_function
    ret = self.client.get_function(FunctionName=func_name)
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/botocore/client.py", line 960, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the GetFunction operation: Function not found: arn:aws:lambda:us-east-1:702948139887:function:220_video_processing_python_3_7

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/justinchigu/serverless-benchmarks/./sebs.py", line 43, in __call__
    return self.main(*args, **kwargs)
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/justinchigu/serverless-benchmarks/./sebs.py", line 85, in wrapper
    return func(*args, **kwargs)
  File "/home/justinchigu/serverless-benchmarks/./sebs.py", line 110, in wrapper
    return func(*args, **kwargs)
  File "/home/justinchigu/serverless-benchmarks/./sebs.py", line 245, in invoke
    func = deployment_client.get_function(
  File "/home/justinchigu/serverless-benchmarks/sebs/faas/system.py", line 174, in get_function
    function = self.create_function(code_package, func_name)
  File "/home/justinchigu/serverless-benchmarks/sebs/aws/aws.py", line 211, in create_function
    ret = self.client.create_function(
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/botocore/client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/botocore/client.py", line 943, in _make_api_call
    http, parsed_response = self._make_request(
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/botocore/client.py", line 966, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/botocore/endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/botocore/endpoint.py", line 202, in _send_request
    while self._needs_retry(
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/botocore/endpoint.py", line 354, in _needs_retry
    responses = self._event_emitter.emit(
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/botocore/retryhandler.py", line 207, in __call__
    if self._checker(**checker_kwargs):
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/botocore/retryhandler.py", line 284, in __call__
    should_retry = self._should_retry(
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/botocore/retryhandler.py", line 320, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/botocore/retryhandler.py", line 363, in __call__
    checker_response = checker(
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/botocore/retryhandler.py", line 247, in __call__
    return self._check_caught_exception(
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/botocore/retryhandler.py", line 416, in _check_caught_exception
    raise caught_exception
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/botocore/endpoint.py", line 281, in _do_get_response
    http_response = self._send(request)
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/botocore/endpoint.py", line 377, in _send
    return self.http_session.send(request)
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/botocore/httpsession.py", line 494, in send
    raise ConnectionClosedError(
botocore.exceptions.ConnectionClosedError: Connection was closed before we received a valid response from endpoint URL: "https://lambda.us-east-1.amazonaws.com/2015-03-31/functions".
INFO:Benchmark-2622:Update cached config /home/justinchigu/serverless-benchmarks/cache/aws.json
(python-venv) justinchigu@SeBSVM:~/serverless-benchmarks$

**Comment by mcopik** [comment]
@jchigu This issue is unrelated to SeBS - it seems that `boto3`, the AWS library, could not connect to the AWS cloud. I suggest debugging your network connection - it looks like you cannot connect from your VM to the outside world.

You can verify this by installing the AWS CLI and running a simple command such as `aws lambda list-functions`. If this works, then please reopen the issue and we will continue the investigation. At the moment, the issue seems to be caused by the underlying system.
