### ISSUE TITLE
RuntimeError: Failed invocation of function!

### ISSUE THREAD

**Issue by jchigu** [spcl/serverless-benchmarks#130]
(python-venv) justinchigu@SeBSVM:~/serverless-benchmarks$ ./sebs.py benchmark invoke 120.uploader small --config config/example.json --deployment aws --verbose
01:45:46,573 INFO SeBS-cdee: Created experiment output at /home/justinchigu/serverless-benchmarks
01:45:48,463 INFO AWS.Credentials-b993: Using cached credentials for AWS
01:45:48,464 INFO AWS.Resources-c4d8: Using cached resources for AWS
01:45:48,464 INFO AWS.Config-f132: Using cached config for AWS
01:45:49,221 INFO Benchmark-4635: Using cached benchmark 120.uploader at /home/justinchigu/serverless-benchmarks/cache/120.uploader/aws/python/3.7/120.uploader.zip
01:45:49,223 INFO AWS-ed14: Using cached function 120_uploader_python_3_7 in /home/justinchigu/serverless-benchmarks/cache/120.uploader/aws/python/3.7/120.uploader.zip
01:45:49,223 INFO AWS-ed14: Cached function 120_uploader_python_3_7 is up to date.
01:45:50,334 INFO AWS.S3-2154: Using cached storage input buckets []
01:45:50,335 INFO AWS.S3-2154: Using cached storage output buckets ['120.uploader-0-output-3a27bed7-a7cc-49']
01:45:50,336 INFO SeBS-cdee: Beginning repetition 1/5
01:45:56,789 ERROR AWS.HTTPTrigger-fc7d: Invocation on URL https://3xpbb2oqw6.execute-api.us-east-1.amazonaws.com failed!
01:45:56,792 ERROR AWS.HTTPTrigger-fc7d: Output: {'message': 'Internal Server Error'}
ERROR:root:Failed invocation of function! Output: {'message': 'Internal Server Error'}
Traceback (most recent call last):
  File "/home/justinchigu/serverless-benchmarks/./sebs.py", line 43, in __call__
    return self.main(*args, **kwargs)
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/justinchigu/serverless-benchmarks/./sebs.py", line 85, in wrapper
    return func(*args, **kwargs)
  File "/home/justinchigu/serverless-benchmarks/./sebs.py", line 110, in wrapper
    return func(*args, **kwargs)
  File "/home/justinchigu/serverless-benchmarks/./sebs.py", line 263, in invoke
    ret = trigger.sync_invoke(input_config)
  File "/home/justinchigu/serverless-benchmarks/sebs/aws/triggers.py", line 112, in sync_invoke
    return self._http_invoke(payload, self.url)
  File "/home/justinchigu/serverless-benchmarks/sebs/faas/function.py", line 215, in _http_invoke
    raise RuntimeError(f"Failed invocation of function! Output: {output}")
RuntimeError: Failed invocation of function! Output: {'message': 'Internal Server Error'}
INFO:Benchmark-2244:Update cached config /home/justinchigu/serverless-benchmarks/cache/aws.json
(python-venv) justinchigu@SeBSVM:~/serverless-benchmarks$

**Comment by mcopik** [comment]
@jchigu Thanks for raising the issue! Indeed, GitHub changed the URL of the archive we used as the input for the benchmark.

This has been fixed on the `master` branch.
