### ISSUE TITLE
AttributeError: 'Local' object has no attribute '_measure_interval'

### ISSUE THREAD

**Issue by jchigu** [spcl/serverless-benchmarks#133]
(python-venv) justinchigu@SeBSVM:~/serverless-benchmarks$ ./sebs.py benchmark invoke 110.dynamic-html test --config config/example.json --deployment local --verbose
13:27:33,924 INFO SeBS-e6d2: Created experiment output at /home/justinchigu/serverless-benchmarks
13:27:36,618 INFO Benchmark-d739: Using cached benchmark 110.dynamic-html at /home/justinchigu/serverless-benchmarks/cache/110.dynamic-html/local/python/3.7/code
13:27:36,619 INFO Local-cac1: Creating new function! Reason: function 110.dynamic-html-python-3.7 not found in cache.
ERROR:root:'Local' object has no attribute '_measure_interval'
Traceback (most recent call last):
  File "/home/justinchigu/serverless-benchmarks/./sebs.py", line 43, in __call__
    return self.main(*args, **kwargs)
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/justinchigu/serverless-benchmarks/./sebs.py", line 85, in wrapper
    return func(*args, **kwargs)
  File "/home/justinchigu/serverless-benchmarks/./sebs.py", line 110, in wrapper
    return func(*args, **kwargs)
  File "/home/justinchigu/serverless-benchmarks/./sebs.py", line 245, in invoke
    func = deployment_client.get_function(
  File "/home/justinchigu/serverless-benchmarks/sebs/faas/system.py", line 174, in get_function
    function = self.create_function(code_package, func_name)
  File "/home/justinchigu/serverless-benchmarks/sebs/local/local.py", line 197, in create_function
    str(self._measure_interval),
AttributeError: 'Local' object has no attribute '_measure_interval'
(python-venv) justinchigu@SeBSVM:~/serverless-benchmarks$ ./sebs.py benchmark invoke 120.uploader test --config config/example.json --deployment local --verbose
13:28:14,118 INFO SeBS-2af4: Created experiment output at /home/justinchigu/serverless-benchmarks
13:28:14,775 INFO Benchmark-860d: Using cached benchmark 120.uploader at /home/justinchigu/serverless-benchmarks/cache/120.uploader/local/python/3.7/code
13:28:14,775 INFO Local-3cfc: Creating new function! Reason: function 120.uploader-python-3.7 not found in cache.
ERROR:root:'Local' object has no attribute '_measure_interval'
Traceback (most recent call last):
  File "/home/justinchigu/serverless-benchmarks/./sebs.py", line 43, in __call__
    return self.main(*args, **kwargs)
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/justinchigu/serverless-benchmarks/./sebs.py", line 85, in wrapper
    return func(*args, **kwargs)
  File "/home/justinchigu/serverless-benchmarks/./sebs.py", line 110, in wrapper
    return func(*args, **kwargs)
  File "/home/justinchigu/serverless-benchmarks/./sebs.py", line 245, in invoke
    func = deployment_client.get_function(
  File "/home/justinchigu/serverless-benchmarks/sebs/faas/system.py", line 174, in get_function
    function = self.create_function(code_package, func_name)
  File "/home/justinchigu/serverless-benchmarks/sebs/local/local.py", line 197, in create_function
    str(self._measure_interval),
AttributeError: 'Local' object has no attribute '_measure_interval'
(python-venv) justinchigu@SeBSVM:~/serverless-benchmarks$ ./sebs.py benchmark invoke 311.compression test --config config/example.json --deployment local --verbose
13:28:41,782 INFO SeBS-d2c5: Created experiment output at /home/justinchigu/serverless-benchmarks
13:28:42,354 INFO Benchmark-d576: Using cached benchmark 311.compression at /home/justinchigu/serverless-benchmarks/cache/311.compression/local/python/3.7/code
13:28:42,355 INFO Local-35e6: Creating new function! Reason: function 311.compression-python-3.7 not found in cache.
ERROR:root:'Local' object has no attribute '_measure_interval'
Traceback (most recent call last):
  File "/home/justinchigu/serverless-benchmarks/./sebs.py", line 43, in __call__
    return self.main(*args, **kwargs)
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/justinchigu/serverless-benchmarks/./sebs.py", line 85, in wrapper
    return func(*args, **kwargs)
  File "/home/justinchigu/serverless-benchmarks/./sebs.py", line 110, in wrapper
    return func(*args, **kwargs)
  File "/home/justinchigu/serverless-benchmarks/./sebs.py", line 245, in invoke
    func = deployment_client.get_function(
  File "/home/justinchigu/serverless-benchmarks/sebs/faas/system.py", line 174, in get_function
    function = self.create_function(code_package, func_name)
  File "/home/justinchigu/serverless-benchmarks/sebs/local/local.py", line 197, in create_function
    str(self._measure_interval),
AttributeError: 'Local' object has no attribute '_measure_interval'
(python-venv) justinchigu@SeBSVM:~/serverless-benchmarks$

**Comment by mcopik** [comment]
@jchigu Thanks for the bug report! It will be fixed soon.

**Comment by mcopik** [comment]
Resolved with #136
