### ISSUE TITLE
GCP error : ERROR:root:('Connection aborted.', timeout('The write operation timed out'))

### ISSUE THREAD

**Issue by jchigu** [spcl/serverless-benchmarks#151]
(python-venv) root@localhost:~/serverless-benchmarks# ./sebs.py benchmark invoke 502.graph-mst test --config config/example.json --deployment gcp --v
erbose --update-code --update-storage
[10:49:03.178547] SeBS-9993 Created experiment output at /root/serverless-benchmarks
[10:49:04.406673] GCPCredentials-352b Using cached credentials for GCP
[10:49:04.413783] GCPResources-165b No cached resources for GCP found, using user configuration.
[10:49:04.414520] GCPConfig-ef41 Loading cached config for GCP
[10:49:05.331152] Benchmark-7afe Building benchmark 502.graph-mst. Reason: no cached code package.
[10:49:05.442220] Benchmark-7afe Docker build of benchmark dependencies in container of image spcleth/serverless-benchmarks:build.gcp.python.3.7
[10:49:05.442990] Benchmark-7afe Docker mount of benchmark code from path /root/serverless-benchmarks/502.graph-mst_code/python/3.7
[10:49:53.651673] Benchmark-7afe Created code package (source hash: e6f7d5c24ac1290ac17f65d8b540996e), for run on gcp with python:3.7
[10:49:53.692067] GCP-c4e6 Creating new function! Reason: function function-502_graph_mst_python_3_7 not found in cache.
ERROR:root:('Connection aborted.', timeout('The write operation timed out'))
Traceback (most recent call last):
  File "/root/serverless-benchmarks/python-venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/root/serverless-benchmarks/python-venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/root/serverless-benchmarks/python-venv/lib/python3.8/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1050, in _send_output
    self.send(chunk)
  File "/usr/lib/python3.8/http/client.py", line 972, in send
    self.sock.sendall(data)
  File "/usr/lib/python3.8/ssl.py", line 1204, in sendall
    v = self.send(byte_view[count:])
  File "/usr/lib/python3.8/ssl.py", line 1173, in send
    return self._sslobj.write(data)
socket.timeout: The write operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/serverless-benchmarks/python-venv/lib/python3.8/site-packages/requests/adapters.py", line 495, in send
    resp = conn.urlopen(
  File "/root/serverless-benchmarks/python-venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/root/serverless-benchmarks/python-venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/root/serverless-benchmarks/python-venv/lib/python3.8/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/root/serverless-benchmarks/python-venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/root/serverless-benchmarks/python-venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/root/serverless-benchmarks/python-venv/lib/python3.8/site-packages/urllib3/connection.py", line 244, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1050, in _send_output
    self.send(chunk)
  File "/usr/lib/python3.8/http/client.py", line 972, in send
    self.sock.sendall(data)
  File "/usr/lib/python3.8/ssl.py", line 1204, in sendall
    v = self.send(byte_view[count:])
  File "/usr/lib/python3.8/ssl.py", line 1173, in send
    return self._sslobj.write(data)
urllib3.exceptions.ProtocolError: ('Connection aborted.', timeout('The write operation timed out'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./sebs.py", line 30, in __call__
    return self.main(*args, **kwargs)
  File "/root/serverless-benchmarks/python-venv/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/root/serverless-benchmarks/python-venv/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/serverless-benchmarks/python-venv/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/serverless-benchmarks/python-venv/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/serverless-benchmarks/python-venv/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "./sebs.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "./sebs.py", line 97, in wrapper
    return func(*args, **kwargs)
  File "./sebs.py", line 233, in invoke
    func = deployment_client.get_function(
  File "/root/serverless-benchmarks/sebs/faas/system.py", line 174, in get_function
    function = self.create_function(code_package, func_name)
  File "/root/serverless-benchmarks/sebs/gcp/gcp.py", line 206, in create_function
    storage_client.upload(code_bucket, package, code_package_name)
  File "/root/serverless-benchmarks/sebs/gcp/storage.py", line 66, in upload
    blob.upload_from_filename(filepath)
  File "/root/serverless-benchmarks/python-venv/lib/python3.8/site-packages/google/cloud/storage/blob.py", line 2338, in upload_from_filename
    self.upload_from_file(
  File "/root/serverless-benchmarks/python-venv/lib/python3.8/site-packages/google/cloud/storage/blob.py", line 2224, in upload_from_file
    created_json = self._do_upload(
  File "/root/serverless-benchmarks/python-venv/lib/python3.8/site-packages/google/cloud/storage/blob.py", line 2071, in _do_upload
    response = self._do_resumable_upload(
  File "/root/serverless-benchmarks/python-venv/lib/python3.8/site-packages/google/cloud/storage/blob.py", line 1950, in _do_resumable_upload
    response = upload.transmit_next_chunk(transport, timeout=timeout)
  File "/root/serverless-benchmarks/python-venv/lib/python3.8/site-packages/google/resumable_media/requests/upload.py", line 496, in transmit_next_chunk
    response = _request_helpers.http_request(
  File "/root/serverless-benchmarks/python-venv/lib/python3.8/site-packages/google/resumable_media/requests/_request_helpers.py", line 136, in http_request
    return _helpers.wait_and_retry(func, RequestsMixin._get_status_code, retry_strategy)
  File "/root/serverless-benchmarks/python-venv/lib/python3.8/site-packages/google/resumable_media/_helpers.py", line 188, in wait_and_retry
    raise error
  File "/root/serverless-benchmarks/python-venv/lib/python3.8/site-packages/google/resumable_media/_helpers.py", line 177, in wait_and_retry
    response = func()
  File "/root/serverless-benchmarks/python-venv/lib/python3.8/site-packages/google/auth/transport/requests.py", line 480, in request
    response = super(AuthorizedSession, self).request(
  File "/root/serverless-benchmarks/python-venv/lib/python3.8/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/serverless-benchmarks/python-venv/lib/python3.8/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/root/serverless-benchmarks/python-venv/lib/python3.8/site-packages/requests/adapters.py", line 553, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', timeout('The write operation timed out'))
[11:16:46.436277] Benchmark-5698 Update cached config /root/serverless-benchmarks/cache/aws.json

**Comment by mcopik** [comment]
@jchigu I cannot reproduce the issue. Please follow the template for bug reports (it appears automatically when you open a new issue), provide all necessary information, and format logging outputs correctly (use Markdown's fenced code block).

Since you are timing out at the operation of connecting to a Google Cloud API, it does seem like an issue with network connectivity and encryption which you experienced before.

Once you provide the requested information, I will be happy to reopen the issue and investigate.
