### ISSUE TITLE
ERROR root [SSL: SHUTDOWN_WHILE_IN_INIT] shutdown while in init (_ssl.c:2548) 

### ISSUE THREAD

**Issue by jchigu** [spcl/serverless-benchmarks#156]
**Describe the bug**
I am running perf-cost on GCP 
**To Reproduce**
1. Go to '.../serverless-benchmarks/'
2. Run the command './sebs.py experiment invoke perf-cost --config config/example.json --deployment gcp --verbose' 
3. Scroll down the entire log provided. Some times it is saying GCP-46a0 Redeployed 0 out of 1 then 
    'Experiment.PerfCost-6a08 Processed 11 samples out of 50, 85 errors' - is there an explanation for this log
5. See the error
ERROR:root:[SSL: SHUTDOWN_WHILE_IN_INIT] shutdown while in init (_ssl.c:2548)

**Expected behavior**

**Logs**
Please provide the output of SeBS commands causing the problem, executed with the flag `--verbose`. Please use the Markdown fenced code blocks (``` ... ```) to format error logs.
(python-venv) justinchigu@SeBS:~/serverless-benchmarks$ ./sebs.py experiment invoke perf-cost --config config/example.json --deployment gcp --verbose
[01:17:59.251873] SeBS-5fac Created experiment output at /home/justinchigu/serverless-benchmarks
[01:18:00.072046] GCPCredentials-196c Using cached credentials for GCP
[01:18:00.072688] GCPResources-ad7d No cached resources for GCP found, using user configuration.
[01:18:00.074226] GCPConfig-1613 Loading cached config for GCP
[01:18:00.773403] Benchmark-897b Using cached benchmark 120.uploader at /home/justinchigu/serverless-benchmarks/cache/120.uploader/gcp/python/3.7/120.uploader.zip
[01:18:00.776265] GCP-c355 Using cached function function-120_uploader_python_3_7 in /home/justinchigu/serverless-benchmarks/cache/120.uploader/gcp/python/3.7/120.uploader.zip
[01:18:00.777388] GCP-c355 Cached function function-120_uploader_python_3_7 is up to date.
[01:18:02.066052] GCP.GCPStorage-e697 Using cached storage input buckets ['120_uploader-0-input-832734ef-bb85-4c']
[01:18:02.066447] GCP.GCPStorage-e697 Using cached storage output buckets ['120_uploader-0-output-0ca80ae5-7520-46']
[01:18:02.069508] Experiment.PerfCost-bf08 Begin experiment on memory size 256
[01:18:05.221253] GCP-c355 Uploaded new code package to 120_uploader-0-input-832734ef-bb85-4c/120.uploader.zip
[01:19:45.476884] GCP-c355 Published new function code and configuration.
[01:19:45.478819] Experiment.PerfCost-bf08 Begin cold experiments
[01:19:45.996570] GCP-c355 Redeployed 0 out of 1
[01:19:51.090798] GCP-c355 Redeployed 0 out of 1
[01:19:56.192968] GCP-c355 Redeployed 0 out of 1
[01:21:04.133283] GCP-c355 Redeployed 0 out of 1
[01:21:09.324146] GCP-c355 Redeployed 0 out of 1
[01:21:14.432782] GCP-c355 Redeployed 0 out of 1
[01:21:19.537155] GCP-c355 Redeployed 0 out of 1
[01:21:24.663595] GCP-c355 Redeployed 0 out of 1
[01:21:29.888962] GCP-c355 Redeployed 1 out of 1
[01:21:34.897239] GCP.HTTPTrigger-4e34 Invoke function https://europe-west1-serverlessbenchmarksgcp.cloudfunctions.net/function-120_uploader_python_3_7
[[01:21:34.951490] GCP.HTTPTrigger-4e34 Invoke function https://europe-west1-serverlessbenchmarksgcp.cloudfunctions.net/function-120_uploader_python_3_7
[01:21:55.557597] Experiment.PerfCost-bf08 Processed 0 warm-up samples, ignoring these results.
[01:22:00.927557] GCP-c355 Redeployed 0 out of 1
[01:22:06.046430] GCP-c355 Redeployed 0 out of 1
[01:22:11.198353] GCP-c355 Redeployed 0 out of 1
[01:23:07.497557] GCP-c355 Redeployed 0 out of 1
[01:23:12.672921] GCP-c355 Redeployed 0 out of 1
[01:23:17.787482] GCP-c355 Redeployed 1 out of 1
[01:23:22.795344] GCP.HTTPTrigger-4e34 Invoke function https://europe-west1-serverlessbenchmarksgcp.cloudfunctions.net/function-120_uploader_python_3_7
west1-serverlessbenchmarksgcp.cloudfunctions.net/function-120_uploader_python_3_7
[01:23:22.834456] GCP.HTTPTrigger-4e34 Invoke function https://europe-west1-serverlessbenchmarksgcp.cloudfunctions.net/function-120_uploader_python_3_7

[01:23:22.828188] GCP.HTTPTrigger-4e34 Invoke function https://europe-west1-serverlessbenchmarksgcp.cloudfunctions.net/function-120_uploader_python_3_7
[01:23:32.027710] GCP.HTTPTrigger-4e34 Invoke of function was successful
[01:23:40.356180] Experiment.PerfCost-bf08 Processed 1 samples out of 50, 99 errors
[01:23:45.731975] GCP-c355 Redeployed 0 out of 1
[01:25:16.837572] GCP-c355 Redeployed 0 out of 1
[01:25:21.966344] GCP-c355 Redeployed 0 out of 1
[01:25:27.094339] GCP-c355 Redeployed 1 out of 1
[01:25:32.102192] GCP.HTTPTrigger-4e34 Invoke function https://europe-west1-serverlessbenchmarksgcp.cloudfunctions.net/function-120_uploader_python_3_7
[01:25:32.103034] GCP.HTTPTrigger-4e34 Invoke function https://europe-west1-serverlessbenchmarksgcp.cloudfunctions.net/function-120_uploader_python_3_7
[01:25:32.124146] GCP.HTTPTrigger-4e34 Invoke function https://europe-west1-serverlessbenchmarksgcp.cloudfunctions.net/function-120_uploader_python_3_7
[01:25:32.143283] GCP.HTTPTrigger-4e34 Invoke function https://europe-west1-serverlessbenchmarksgcp.cloudfunctions.net/function-120_uploader_python_3_7
[01:25:32.139637] GCP.HTTPTrigger-4e34 Invoke function https://europe-west1-serverlessbenchmarksgcp.cloudfunctions.net/function-120_uploader_python_3_7
[01:25:40.318378] GCP.HTTPTrigger-4e34 Invoke of function was successful
[01:25:42.173413] GCP.HTTPTrigger-4e34 Invoke of function was successful
[01:25:51.435551] Experiment.PerfCost-bf08 Invocation u7174suk5fac is not cold!
[01:25:51.446525] Experiment.PerfCost-bf08 Processed 2 samples out of 50, 147 errors
[01:25:56.852075] GCP-c355 Redeployed 0 out of 1
[01:26:01.954822] GCP-c355 Redeployed 0 out of 1
[[01:27:03.390464] GCP-c355 Redeployed 0 out of 1
[01:27:08.491384] GCP-c355 Redeployed 0 out of 1
[01:27:13.599367] GCP-c355 Redeployed 0 out of 1
[01:27:18.718601] GCP-c355 Redeployed 1 out of 1
[01:27:23.726740] GCP.HTTPTrigger-4e34 Invoke function https://europe-west1-serverlessbenchmarksgcp.cloudfunctions.net/function-120_uploader_python_3_7
[01:27:23.727018] GCP.HTTPTrigger-4e34 Invoke function https://europe-west1-serverlessbenchmarksgcp.cloudfunctions.net/function-120_uploader_python_3_7
Trigger-4e34 Invoke function https://europe-west1-serverlessbenchmarksgcp.cloudfunctions.net/function-120_uploader_python_3_7
[01:27:35.647565] GCP.HTTPTrigger-4e34 Invoke of function was successful
[01:27:36.172723] GCP.HTTPTrigger-4e34 Invoke of function was successful
[01:27:37.956757] GCP.HTTPTrigger-4e34 Invoke of function was successful
[01:27:38.170984] GCP.HTTPTrigger-4e34 Invoke of function was successful
[01:27:38.177568] Experiment.PerfCost-bf08 Processed 6 samples out of 50, 193 errors
[01:27:43.538276] GCP-c355 Redeployed 0 out of 1
[01:27:48.656435] GCP-c355 Redeployed 0 out of 1
[01:27:53.829990] GCP-c355 Redeployed 0 out of 1
[01:27:58.951733] GCP-c355 Redeployed 0 out of 1
[01:28:04.062430] GCP-c355 Redeployed 0 out of 1
[01:28:09.177186] GCP-c355 Redeployed 0 out of 1
[01:28:14.282594] GCP-c355 Redeployed 0 out of 1
[01:28:19.396501] GCP-c355 Redeployed 0 out of 1
[01:28:24.498400] GCP-c355 Redeployed 0 out of 1
[01:28:29.612754] GCP-c355 Redeployed 0 out of 1
[01:28:34.710964] GCP-c355 Redeployed 0 out of 1
[01:28:39.812435] GCP-c355 Redeployed 0 out of 1
[01:28:44.935237] GCP-c355 Redeployed 0 out of 1
[01:28:50.042673] GCP-c355 Redeployed 0 out of 1
[01:28:55.146406] GCP-c355 Redeployed 0 out of 1
[01:29:00.268837] GCP-c355 Redeployed 0 out of 1
[01:29:05.385824] GCP-c355 Redeployed 1 out of 1
[01:29:10.393192] GCP.HTTPTrigger-4e34 Invoke function https://europe-west1-serverlessbenchmarksgcp.cloudfunctions.net/function-120_uploader_python_3_7
[01:29:10.398959] GCP.HTTPTrigger-4e34 Invoke function https://europe-west1-serverlessbenchmarksgcp.cloudfunctions.net/function-
[01:29:12.839644] GCP.HTTPTrigger-4e34 Invoke of function was successful
[01:29:25.349386] GCP.HTTPTrigger-4e34 Invoke of function was successful
[01:29:26.229098] Experiment.PerfCost-bf08 Invocation n73a1dkz2a24 is not cold!
[01:29:26.279038] Experiment.PerfCost-bf08 Processed 7 samples out of 50, 241 errors
[01:29:31.628402] GCP-c355 Redeployed 0 out of 1
[01:29:36.745667] GCP-c355 Redeployed 0 out of 1
[01:29:41.854818] GCP-c355 Redeployed 0 out of 1
[01:29:46.955534] GCP-c355 Redeployed 0 out of 1
[01:29:52.102277] GCP-c355 Redeployed 0 out of 1
[01:29:57.224499] GCP-c355 Redeployed 0 out of 1
[01:30:02.341695] GCP-c355 Redeployed 0 out of 1
[01:30:07.449662] GCP-c355 Redeployed 0 out of 1
[01:30:12.563778] GCP-c355 Redeployed 0 out of 1
[01:30:17.671770] GCP-c355 Redeployed 0 out of 1
[01:30:22.786778] GCP-c355 Redeployed 0 out of 1
[01:30:27.922195] GCP-c355 Redeployed 0 out of 1
[01:30:33.022635] GCP-c355 Redeployed 0 out of 1
[01:30:38.132064] GCP-c355 Redeployed 0 out of 1
[01:30:43.255773] GCP-c355 Redeployed 0 out of 1
[01:30:48.373379] GCP-c355 Redeployed 0 out of 1
[01:30:53.531310] GCP-c355 Redeployed 1 out of 1
[01:30:58.539152] GCP.HTTPTrigger-4e34 Invoke function https://europe-west1-serverlessbenchmarksgcp.cloudfunctions.net/function-120_uploader_python_3_7
[01:30:58.540968] GCP.HTTPTrigger-4e34 Invoke function https://europe-west1-serverlessbenchmarksgcp.cloudfunctions.net/function-120_uploader_python_3_7

[01:30:58.572920] GCP.HTTPTrigger-4e34 Invoke function https://europe-west1-serverlessbenchmarksgcp.cloudfunctions.net/function-120_uploader_python_3_7
[01:31:12.972145] GCP.HTTPTrigger-4e34 Invoke of function was successful
[01:31:14.526984] GCP.HTTPTrigger-4e34 Invoke of function was successful
[01:31:17.264924] Experiment.PerfCost-bf08 Processed 9 samples out of 50, 289 errors
[01:31:22.635705] GCP-c355 Redeployed 0 out of 1
[01:31:27.753993] GCP-c355 Redeployed 0 out of 1
[01:31:32.869876] GCP-c355 Redeployed 0 out of 1
[01:31:37.984759] GCP-c355 Redeployed 0 out of 1
[01:31:43.101420] GCP-c355 Redeployed 0 out of 1
[01:31:48.212964] GCP-c355 Redeployed 0 out of 1
[01:31:53.318945] GCP-c355 Redeployed 0 out of 1
[01:31:58.421988] GCP-c355 Redeployed 0 out of 1
[01:32:03.538762] GCP-c355 Redeployed 0 out of 1
[01:32:08.648071] GCP-c355 Redeployed 0 out of 1
[01:32:13.762736] GCP-c355 Redeployed 0 out of 1
[01:32:18.885958] GCP-c355 Redeployed 0 out of 1
[01:32:23.999666] GCP-c355 Redeployed 0 out of 1
[01:32:29.118102] GCP-c355 Redeployed 0 out of 1
[01:32:34.217904] GCP-c355 Redeployed 0 out of 1
[01:32:39.340885] GCP-c355 Redeployed 0 out of 1
[01:32:44.475102] GCP-c355 Redeployed 1 out of 1
[01:32:49.484558] GCP.HTTPTrigger-4e34 Invoke function https://europe-west1-serverlessbenchmarksgcp.cloudfunctions.net/function-120_uploader_python_3_7
[01:32:49.485642] GCP.HTTPTrigger-4e34 Invoke function https://europe-west1-serverlessbenchmarksgcp.cloudfunctions.net/function-120_uploader_python_3_7
[01:32:49.486281] GCP.HTTPTrigger-4e34 Invoke function https://europe-west1-serverlessbenchmarksgcp.cloudfunctions.net/function-120_uploader_python_3_7

[01:32:49.523670] GCP.HTTPTrigger-4e34 Invoke function https://europe-west1-serverlessbenchmarksgcp.cloudfunctions.net/function-120_uploader_python_3_7
[01:32:59.808042] GCP.HTTPTrigger-4e34 Invoke of function was successful
[01:33:01.110875] GCP.HTTPTrigger-4e34 Invoke of function was successful
[01:33:01.769894] GCP.HTTPTrigger-4e34 Invoke of function was successful
[01:33:02.520624] GCP.HTTPTrigger-4e34 Invoke of function was successful
[01:33:03.164912] GCP.HTTPTrigger-4e34 Invoke of function was successful
[01:33:03.326957] GCP.HTTPTrigger-4e34 Invoke of function was successful
[01:33:04.218259] GCP.HTTPTrigger-4e34 Invoke of function was successful
[01:33:07.033932] GCP.HTTPTrigger-4e34 Invoke of function was successful
[01:33:07.078215] GCP.HTTPTrigger-4e34 Invoke of function was successful
[01:33:07.084250] Experiment.PerfCost-bf08 Processed 18 samples out of 50, 330 errors
[01:33:12.619469] GCP-c355 Redeployed 0 out of 1
[01:33:17.729193] GCP-c355 Redeployed 0 out of 1
[01:33:22.853045] GCP-c355 Redeployed 0 out of 1
[01:33:27.970114] GCP-c355 Redeployed 0 out of 1
[01:33:33.093334] GCP-c355 Redeployed 0 out of 1
[01:33:38.212930] GCP-c355 Redeployed 0 out of 1
[01:33:43.317420] GCP-c355 Redeployed 0 out of 1
[01:33:48.445682] GCP-c355 Redeployed 0 out of 1
[01:33:53.674868] GCP-c355 Redeployed 0 out of 1
[01:33:58.922196] GCP-c355 Redeployed 0 out of 1
[01:34:04.036148] GCP-c355 Redeployed 0 out of 1
[01:34:09.147529] GCP-c355 Redeployed 0 out of 1
[01:34:14.364865] GCP-c355 Redeployed 0 out of 1
[01:34:19.480277] GCP-c355 Redeployed 0 out of 1
[01:34:24.603719] GCP-c355 Redeployed 0 out of 1
[01:34:29.714151] GCP-c355 Redeployed 0 out of 1
[01:34:34.820160] GCP-c355 Redeployed 0 out of 1
[01:34:39.938882] GCP-c355 Redeployed 0 out of 1
[01:34:45.046945] GCP-c355 Redeployed 0 out of 1
[01:34:50.161310] GCP-c355 Redeployed 1 out of 1
[01:34:55.168783] GCP.HTTPTrigger-4e34 Invoke function https://europe-west1-serverlessbenchmarksgcp.cloudfunctions.net/function-120_uploader_python_3_7
[01:34:55.206346] GCP.HTTPTrigger-4e34 Invoke function https://europe-west1-serverlessbenchmarksgcp.cloudfunctions.net/function-120_uploader_python_3_7
[01:34:55.174156] GCP.HTTPTrigger-4e34 Invoke function https://europe-west1-serverlessbenchmarksgcp.cloudfunctions.net/function-120_uploader_python_3_7
[01:34:55.181500] GCP.HTTPTrigger-4e34 Invoke function https://europe-west1-serverlessbenchmarksgcp.cloudfunctions.net/function-120_uploader_python_3_7
[01:34:55.207075] GCP.HTTPTrigger-4e34 Invoke function https://europe-west1-serverlessbenchmarksgcp.cloudfunctions.net/function-120_uploader_python_3_7
[01:34:55.208250] GCP.HTTPTrigger-4e34 Invoke function https://europe-west1-serverlessbenchmarksgcp.cloudfunctions.net/function-120_uploader_python_3_7
[01:35:02.582694] GCP.HTTPTrigger-4e34 Invoke of function was successful
[01:35:03.951545] GCP.HTTPTrigger-4e34 Invoke of function was successful
[01:35:04.901575] GCP.HTTPTrigger-4e34 Invoke of function was successful
[01:35:05.565980] GCP.HTTPTrigger-4e34 Invoke of function was successful
[01:35:10.610627] GCP.HTTPTrigger-4e34 Invoke of function was successful
[01:35:11.186408] Experiment.PerfCost-bf08 Invocation oloxlahdf680 is not cold!
[01:35:11.285055] Experiment.PerfCost-bf08 Invocation oloxv2b4a7f0 is not cold!
[01:35:11.286748] Experiment.PerfCost-bf08 Invocation olox8tls246a is not cold!
[01:35:11.287101] Experiment.PerfCost-bf08 Processed 20 samples out of 50, 375 errors
[01:35:16.657555] GCP-c355 Redeployed 0 out of 1
[01:35:21.765572] GCP-c355 Redeployed 0 out of 1
[01:35:26.869878] GCP-c355 Redeployed 0 out of 1
[01:35:31.972942] GCP-c355 Redeployed 0 out of 1
[01:35:37.082625] GCP-c355 Redeployed 0 out of 1
[01:35:42.177662] GCP-c355 Redeployed 0 out of 1
[01:35:47.276809] GCP-c355 Redeployed 0 out of 1
[01:35:52.421293] GCP-c355 Redeployed 0 out of 1
[01:36:49.607548] GCP-c355 Redeployed 1 out of 1
[01:36:54.615307] GCP.HTTPTrigger-4e34 Invoke function https://europe-west1-serverlessbenchmarksgcp.cloudfunctions.net/function-120_uploader_python_3_7
[01:36:54.631930] GCP.HTTPTrigger-4e34 Invoke function https://europe-west1-serverlessbenchmarksgcp.cloudfunctions.net/function-120_uploader_python_3_7
[01:36:58.204180] GCP.HTTPTrigger-4e34 Invoke of function was successful
[01:36:58.456744] GCP.HTTPTrigger-4e34 Invoke of function was successful
[01:36:58.581068] GCP.HTTPTrigger-4e34 Invoke of function was successful
[01:36:58.584317] GCP.HTTPTrigger-4e34 Invoke of function was successful
[01:37:01.320999] GCP.HTTPTrigger-4e34 Invoke of function was successful
[01:37:03.092384] GCP.HTTPTrigger-4e34 Invoke of function was successful
[01:37:03.366108] GCP.HTTPTrigger-4e34 Invoke of function was successful
[01:37:03.483454] GCP.HTTPTrigger-4e34 Invoke of function was successful
[01:37:03.493487] GCP.HTTPTrigger-4e34 Invoke of function was successful
[01:37:03.594437] GCP.HTTPTrigger-4e34 Invoke of function was successful
[01:37:04.600132] GCP.HTTPTrigger-4e34 Invoke of function was successful
[01:37:04.620813] GCP.HTTPTrigger-4e34 Invoke of function was successful
[01:37:04.651437] GCP.HTTPTrigger-4e34 Invoke of function was successful
[01:37:05.028340] GCP.HTTPTrigger-4e34 Invoke of function was successful
[01:37:05.367122] GCP.HTTPTrigger-4e34 Invoke of function was successful
[01:37:05.384786] GCP.HTTPTrigger-4e34 Invoke of function was successful
[01:37:05.402561] GCP.HTTPTrigger-4e34 Invoke of function was successful
[01:37:05.745024] GCP.HTTPTrigger-4e34 Invoke of function was successful
[01:37:05.915193] Experiment.PerfCost-bf08 Invocation wo8bhdtuxe40 is not cold!
[01:37:05.915631] Experiment.PerfCost-bf08 Invocation 0fpbmww2gx5c is not cold!
[01:37:05.915838] Experiment.PerfCost-bf08 Invocation wo8boa82xee6 is not cold!
[01:37:05.985257] Experiment.PerfCost-bf08 Invocation uhm6zs0y34sb is not cold!
[01:37:05.985583] Experiment.PerfCost-bf08 Invocation 9f4e074ns1je is not cold!
[01:37:06.062039] GCP.HTTPTrigger-4e34 Invoke of function was successful
[01:37:06.068611] Experiment.PerfCost-bf08 Invocation d939z7cpoyrp is not cold!
[01:37:06.069360] Experiment.PerfCost-bf08 Invocation zii2w011jjhe is not cold!
[01:37:06.070178] Experiment.PerfCost-bf08 Invocation amri4j430k4l is not cold!
[01:37:06.070405] Experiment.PerfCost-bf08 Invocation uhm6x1bzcrck is not cold!
[01:37:06.070490] Experiment.PerfCost-bf08 Invocation uhm6ry6bzbpn is not cold!
[01:37:06.070699] Experiment.PerfCost-bf08 Invocation wo8bq0pmhsdv is not cold!
[01:37:06.070811] Experiment.PerfCost-bf08 Processed 28 samples out of 50, 406 errors
[01:37:11.422241] GCP-c355 Redeployed 0 out of 1
[01:37:16.557682] GCP-c355 Redeployed 0 out of 1
[01:37:21.674104] GCP-c355 Redeployed 0 out of 1
[01:37:26.795000] GCP-c355 Redeployed 0 out of 1
[01:37:31.893820] GCP-c355 Redeployed 0 out of 1
[01:37:37.005951] GCP-c355 Redeployed 0 out of 1
[01:37:42.114262] GCP-c355 Redeployed 0 out of 1
[01:37:47.230634] GCP-c355 Redeployed 0 out of 1
[01:37:52.337797] GCP-c355 Redeployed 0 out of 1
[01:37:57.445641] GCP-c355 Redeployed 0 out of 1
[01:38:02.547498] GCP-c355 Redeployed 0 out of 1
[01:38:07.658817] GCP-c355 Redeployed 0 out of 1
[01:38:12.767031] GCP-c355 Redeployed 0 out of 1
[01:38:17.875019] GCP-c355 Redeployed 0 out of 1
[01:38:22.969991] GCP-c355 Redeployed 0 out of 1
[01:38:28.072777] GCP-c355 Redeployed 0 out of 1
[01:38:33.188149] GCP-c355 Redeployed 0 out of 1
[01:38:38.304110] GCP-c355 Redeployed 0 out of 1
[01:38:43.441651] GCP-c355 Redeployed 0 out of 1
[01:38:48.561396] GCP-c355 Redeployed 0 out of 1
[01:38:53.676955] GCP-c355 Redeployed 0 out of 1
[01:38:58.790075] GCP-c355 Redeployed 1 out of 1
[01:39:03.797348] GCP.HTTPTrigger-4e34 Invoke function https://europe-west1-serverlessbenchmarksgcp.cloudfunctions.net/function-120_uploader_python_3_7
[01:39:03.798065] GCP.HTTPTrigger-4e34 Invoke function https://europe-west1-serverlessbenchmarksgcp.cloudfunctions.net/function-120_uploader_python_3_7
[01:39:03.799351] GCP.HTTPTrigger-4e34 Invoke function https://europe-west1-serverlessbenchmarksgcp.cloudfunctions.net/function-120_uploader_python_3_7
[01:39:03.801531] GCP.HTTPTrigger-4e34 Invoke function https://europe-west1-serverlessbenchmarksgcp.cloudfunctions.net/function-120_uploader_python_3_7
[01:39:03.802918] GCP.HTTPTrigger-4e34 Invoke function https://europe-west1-serverlessbenchmarksgcp.cloudfunctions.net/function-120_uploader_python_3_7
[01:39:03.807200] GCP.HTTPTrigger-4e34 Invoke function https://europe-west1-serverlessbenchmarksgcp.cloudfunctions.net/function-120_uploader_python_3_7
[01:39:03.807311] GCP.HTTPTrigger-4e34 Invoke function https://europe-west1-serverlessbenchmarksgcp.cloudfunctions.net/function-120_uploader_python_3_7
[01:39:03.804932] GCP.HTTPTrigger-4e34 Invoke function https://europe-west1-serverlessbenchmarksgcp.cloudfunctions.net/function-120_uploader_python_3_7
[01:39:03.811479] GCP.HTTPTrigger-4e34 Invoke function https://europe-west1-serverlessbenchmarksgcp.cloudfunctions.net/function-120_uploader_python_3_7
[01:39:03.808423] GCP.HTTPTrigger-4e34 Invoke function https://europe-west1-serverlessbenchmarksgcp.cloudfunctions.net/function-120_uploader_python_3_7
[01:39:03.809404] GCP.HTTPTrigger-4e34 Invoke function https://europe-west1-serverlessbenchmarksgcp.cloudfunctions.net/function-120_uploader_python_3_7
[01:39:03.813652] GCP.HTTPTrigger-4e34 Invoke function https://europe-west1-serverlessbenchmarksgcp.cloudfunctions.net/function-120_uploader_python_3_7
[01:39:03.815088] GCP.HTTPTrigger-4e34 Invoke function https://europe-west1-serverlessbenchmarksgcp.cloudfunctions.net/function-120_uploader_python_3_7
[01:39:03.822610] GCP.HTTPTrigger-4e34 Invoke function https://europe-west1-serverlessbenchmarksgcp.cloudfunctions.net/function-120_uploader_python_3_7
[01:39:03.824939] GCP.HTTPTrigger-4e34 Invoke function https://europe-west1-serverlessbenchmarksgcp.cloudfunctions.net/function-120_uploader_python_3_7
[01:39:10.561256] GCP.HTTPTrigger-4e34 Invoke of function was successful
[01:39:11.554219] GCP.HTTPTrigger-4e34 Invoke of function was successful
[01:39:12.826193] GCP.HTTPTrigger-4e34 Invoke of function was successful
[01:39:12.954941] GCP.HTTPTrigger-4e34 Invoke of function was successful
[01:39:14.189311] GCP.HTTPTrigger-4e34 Invoke of function was successful
[01:39:14.420083] GCP.HTTPTrigger-4e34 Invoke of function was successful
[01:39:14.877072] Experiment.PerfCost-bf08 Invocation kgjh3lcepnqs is not cold!
[01:39:19.970362] Experiment.PerfCost-bf08 Invocation a22yo8vbr3ck is not cold!
[01:39:19.973048] Experiment.PerfCost-bf08 Invocation a22yccduxbyw is not cold!
[01:39:19.973382] Experiment.PerfCost-bf08 Invocation kgjhtbj20kym is not cold!
[01:39:20.089539] Experiment.PerfCost-bf08 Processed 30 samples out of 50, 450 errors
ERROR:root:[SSL: SHUTDOWN_WHILE_IN_INIT] shutdown while in init (_ssl.c:2548)
Traceback (most recent call last):
  File "/home/justinchigu/serverless-benchmarks/./sebs.py", line 30, in __call__
    return self.main(*args, **kwargs)
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/justinchigu/serverless-benchmarks/./sebs.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/justinchigu/serverless-benchmarks/./sebs.py", line 97, in wrapper
    return func(*args, **kwargs)
  File "/home/justinchigu/serverless-benchmarks/./sebs.py", line 464, in experiment_invoke
    experiment.run()
  File "/home/justinchigu/serverless-benchmarks/sebs/experiments/perf_cost.py", line 85, in run
    self.run_configuration(settings, settings["repetitions"], suffix=str(memory))
  File "/home/justinchigu/serverless-benchmarks/sebs/experiments/perf_cost.py", line 232, in run_configuration
    self._run_configuration(
  File "/home/justinchigu/serverless-benchmarks/sebs/experiments/perf_cost.py", line 156, in _run_configuration
    self._deployment_client.enforce_cold_start(
  File "/home/justinchigu/serverless-benchmarks/sebs/gcp/gcp.py", line 541, in enforce_cold_start
    new_versions.append((self._enforce_cold_start(func), func))
  File "/home/justinchigu/serverless-benchmarks/sebs/gcp/gcp.py", line 532, in _enforce_cold_start
    res = req.execute()
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/googleapiclient/_helpers.py", line 134, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/googleapiclient/http.py", line 900, in execute
    resp, content = _retry_request(
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/googleapiclient/http.py", line 204, in _retry_request
    raise exception
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/googleapiclient/http.py", line 177, in _retry_request
    resp, content = http.request(uri, method, *args, **kwargs)
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/google_auth_httplib2.py", line 218, in request
    response, content = self.http.request(
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/httplib2/__init__.py", line 1724, in request
    (response, content) = self._request(
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/httplib2/__init__.py", line 1444, in _request
    (response, content) = self._conn_request(conn, request_uri, method, body, headers)
  File "/home/justinchigu/serverless-benchmarks/python-venv/lib/python3.10/site-packages/httplib2/__init__.py", line 1396, in _conn_request
    response = conn.getresponse()
  File "/usr/lib/python3.10/http/client.py", line 1374, in getresponse
    response.begin()
  File "/usr/lib/python3.10/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.10/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.10/socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.10/ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.10/ssl.py", line 1130, in read
    return self._sslobj.read(len, buffer)
ssl.SSLError: [SSL: SHUTDOWN_WHILE_IN_INIT] shutdown while in init (_ssl.c:2548)
[01:39:25.118610] Benchmark-6835 Update cached config /home/justinchigu/serverless-benchmarks/cache/gcp.json
(python-venv) justinchigu@SeBS:~/serverless-benchmarks$ 

**System (please complete the following information):**
 - SeBS version (release, branch, git commit)
 - Python version - 3.10
 - OS - Windows Virtual Box 7.0, Ubuntu 22.04

**Additional context**

**Comment by mcopik** [comment]
@jchigu Does this issue persist? Did you experience this on other platforms or only on GCP?

This sounds like another SSL issue - the problem happens while executing a Google cloud query.

**Comment by mcopik** [comment]
@jchigu Does the issue still persist?
