### ISSUE TITLE
ERROR:root: Running perf-cost experiment on Openwhisk

### ISSUE THREAD

**Issue by jchigu** [spcl/serverless-benchmarks#172]
**Describe the bug**
'''I am facing the above-mentioned Error: root when I try to run the experiment of Openwhisk after a successful regression test.'''

**To Reproduce**

1. Go to '...'  terminal
2. Run the command '....' ./sebs.py benchmark regression test --config config/openwhisk.json --deployment openwhisk --benchmark-name 110.dynamic-html
3. Run the command '....' ./sebs.py experiment invoke perf-cost --config config/openwhisk.json --deployment openwhisk
5. Scroll down to '....' the logs below
6. See the error : on the invoking the perf-cost experiment just after Experiment.PerfCost-8c21 Begin cold experiments

**Expected behavior**
I am expecting the function to run since it succeeded the regression test.
**Logs**
Please provide the output of SeBS commands causing the problem, executed with the flag `--verbose`. Please use the Markdown fenced code blocks (``` ... ```) to format error logs.

```
(''' (python-venv) j@DESKTOP-68S4M6E:~/serverless-benchmarks$ rm -r regression-cache/
(python-venv) j@DESKTOP-68S4M6E:~/serverless-benchmarks$ rm -r regression-output/
(python-venv) j@DESKTOP-68S4M6E:~/serverless-benchmarks$ ./sebs.py benchmark regression test --config config/openwhisk.json --deployment openwhisk --benchmark-name 110.dynamic-html
[17:36:18.418510] SeBS-6041 Created experiment output at /home/j/serverless-benchmarks/regression-output
Skip test test_openwhisk_120.uploader
Skip test test_openwhisk_210.thumbnailer
Skip test test_openwhisk_220.video-processing
Skip test test_openwhisk_311.compression
Skip test test_openwhisk_411.image-recognition
Skip test test_openwhisk_501.graph-pagerank
Skip test test_openwhisk_502.graph-mst
Skip test test_openwhisk_503.graph-bfs
Skip test test_openwhisk_504.dna-visualisation
[17:36:24.087977] OpenWhisk.Resources-ea09 Using user-provided Docker registry for OpenWhisk.
[17:36:24.088320] OpenWhisk.Resources-ea09 Using user-provided configuration of storage for OpenWhisk.
[17:36:24.088749] OpenWhisk.Resources-ea09 User-provided configuration is different from cached storage, we will update existing OpenWhisk actions.
[17:36:24.090263] Regression-openwhisk-110.dynamic-html Begin regression test of 110.dynamic-html on openwhisk.
[17:36:24.558378] Benchmark-7b61 Building benchmark 110.dynamic-html. Reason: no cached code package.
[17:36:24.680936] Benchmark-7b61 There is no Docker build image for openwhisk run in python, thus skipping the Docker-based installation of dependencies.
[17:36:28.483516] OpenWhisk-046a Skipping building OpenWhisk Docker package for 110.dynamic-html, using Docker image spcleth/serverless-benchmarks:function.openwhisk.110.dynamic-html.python-3.7 from registry: Docker Hub.
[17:36:28.493432] OpenWhisk-046a Created /home/j/serverless-benchmarks/regression-output/110.dynamic-html_code/python/3.7/110.dynamic-html.zip archive
[17:36:28.496985] OpenWhisk-046a Zip archive size 0.000732 MB
[17:36:28.502498] Benchmark-7b61 Created code package (source hash: 4ac405ed1376b2cc79444be258a42bad), for run on openwhisk with python:3.7
[17:36:28.508683] OpenWhisk-046a Creating new function! Reason: function 110.dynamic-html-python-3.7 not found in cache.
[17:36:28.509043] OpenWhisk-046a Creating function as an action in OpenWhisk.
[17:36:29.366387] OpenWhisk-046a Retrieved existing OpenWhisk action 110.dynamic-html-python-3.7.
[17:36:29.366675] OpenWhisk-046a Update an existing OpenWhisk action 110.dynamic-html-python-3.7.
[17:36:43.010470] Regression-openwhisk-110.dynamic-html 110.dynamic-html success on trigger: TriggerType.HTTP
Succesfully executed 1 out of 1 functions
- 110.dynamic-html
[17:36:43.091206] Benchmark-07a1 Update cached config /home/j/serverless-benchmarks/regression-cache/openwhisk.json
(python-venv) j@DESKTOP-68S4M6E:~/serverless-benchmarks$ cd config/
(python-venv) j@DESKTOP-68S4M6E:~/serverless-benchmarks/config$ nano openwhisk.json
(python-venv) j@DESKTOP-68S4M6E:~/serverless-benchmarks/config$ nano example.json
(python-venv) j@DESKTOP-68S4M6E:~/serverless-benchmarks/config$ cd ..
(python-venv) j@DESKTOP-68S4M6E:~/serverless-benchmarks$ ./sebs.py experiment invoke perf-cost --config config/openwhisk.json --deployment openwhisk
[17:46:19.951410] SeBS-50ad Created experiment output at /home/j/serverless-benchmarks
[17:46:21.485416] OpenWhisk.Resources-7f8f Using user-provided Docker registry for OpenWhisk.
[17:46:21.485580] OpenWhisk.Resources-7f8f Using user-provided configuration of storage for OpenWhisk.
[17:46:21.485839] OpenWhisk.Resources-7f8f User-provided configuration is different from cached storage, we will update existing OpenWhisk actions.
[17:46:21.497791] Benchmark-07d1 Building benchmark 110.dynamic-html. Reason: no cached code package.
[17:46:21.562543] Benchmark-07d1 There is no Docker build image for openwhisk run in python, thus skipping the Docker-based installation of dependencies.
[17:46:24.863406] OpenWhisk-b002 Skipping building OpenWhisk Docker package for 110.dynamic-html, using Docker image spcleth/serverless-benchmarks:function.openwhisk.110.dynamic-html.python-3.7 from registry: Docker Hub.
[17:46:24.874139] OpenWhisk-b002 Created /home/j/serverless-benchmarks/110.dynamic-html_code/python/3.7/110.dynamic-html.zip archive
[17:46:24.874498] OpenWhisk-b002 Zip archive size 0.000732 MB
[17:46:24.883230] Benchmark-07d1 Created code package (source hash: 4ac405ed1376b2cc79444be258a42bad), for run on openwhisk with python:3.7
[17:46:24.890348] OpenWhisk-b002 Creating new function! Reason: function 110.dynamic-html-python-3.7 not found in cache.
[17:46:24.890680] OpenWhisk-b002 Creating function as an action in OpenWhisk.
[17:46:25.829511] OpenWhisk-b002 Retrieved existing OpenWhisk action 110.dynamic-html-python-3.7.
[17:46:25.829982] OpenWhisk-b002 Update an existing OpenWhisk action 110.dynamic-html-python-3.7.
[17:46:26.847158] Experiment.PerfCost-8c21 Begin experiment on memory size 128
[17:46:26.847492] OpenWhisk-b002 Update an existing OpenWhisk action 110.dynamic-html-python-3.7.
[17:46:27.213603] Experiment.PerfCost-8c21 Begin cold experiments
ERROR:root:
Traceback (most recent call last):
  File "/home/j/serverless-benchmarks/./sebs.py", line 30, in __call__
    return self.main(*args, **kwargs)
  File "/home/j/serverless-benchmarks/python-venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/j/serverless-benchmarks/python-venv/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/j/serverless-benchmarks/python-venv/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/j/serverless-benchmarks/python-venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/j/serverless-benchmarks/python-venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/j/serverless-benchmarks/./sebs.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/j/serverless-benchmarks/./sebs.py", line 97, in wrapper
    return func(*args, **kwargs)
  File "/home/j/serverless-benchmarks/./sebs.py", line 464, in experiment_invoke
    experiment.run()
  File "/home/j/serverless-benchmarks/sebs/experiments/perf_cost.py", line 85, in run
    self.run_configuration(settings, settings["repetitions"], suffix=str(memory))
  File "/home/j/serverless-benchmarks/sebs/experiments/perf_cost.py", line 230, in run_configuration
    self._run_configuration(
  File "/home/j/serverless-benchmarks/sebs/experiments/perf_cost.py", line 156, in _run_configuration
    self._deployment_client.enforce_cold_start(
  File "/home/j/serverless-benchmarks/sebs/openwhisk/openwhisk.py", line 369, in enforce_cold_start
    raise NotImplementedError()
NotImplementedError
[17:46:27.256804] Benchmark-b764 Update cached config /home/j/serverless-benchmarks/cache/openwhisk.json
(python-venv) j@DESKTOP-68S4M6E:~/serverless-benchmarks$ ''')
```

**System (please complete the following information):**
 - SeBS version (release, branch, git commit) 
 - Python version 3.7
 - OS ubuntu 22.04 on WSL2

**Additional context**

**Comment by mcopik** [comment]
@jchigu This is a known issue - see #104. Currently, we do not support cold initialization for OpenWhisk. You can use `sequential` and `warm` modes for the `perf-cost` experiment. At the moment, I cannot provide an estimation for when we will be able to resolve this issue.

Closing as duplicate. Also, please follow the instructions next time and format your report as request. Runtime logs are unreadable without Markdown syntax for code blocks.
