### ISSUE TITLE
Azure credential creation script doesn't work

### ISSUE THREAD

**Issue by nurSaadat** [spcl/serverless-benchmarks#176]
**Describe the bug**
When trying to connect to azure, a script is provided to create a user automatically and create credentials. However, the script doesn't work for me. 

**To Reproduce**
1. Activate python env
2. Go to `tools/`
3. Run the command `./create_azure_credentials.py`
4. Follow `Enter intended principal name` command
5. See the error

**Expected behavior**
The program proceeds asking other data or creates Azure account.

**Logs**
```
Traceback (most recent call last):
  File "/root/serverless-benchmarks/python-venv/lib/python3.10/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/root/serverless-benchmarks/python-venv/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.43/containers/19b3cdbf671fd3ccfcf5757018a91c74beb95c47361a17984b6e8829d14f9cb8/exec

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/serverless-benchmarks/tools/./create_azure_credentials.py", line 43, in <module>
    _, out = container.exec_run("az login", user="docker_user", stream=True)
  File "/root/serverless-benchmarks/python-venv/lib/python3.10/site-packages/docker/models/containers.py", line 194, in exec_run
    resp = self.client.api.exec_create(
  File "/root/serverless-benchmarks/python-venv/lib/python3.10/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/root/serverless-benchmarks/python-venv/lib/python3.10/site-packages/docker/api/exec_api.py", line 79, in exec_create
    return self._result(res, True)
  File "/root/serverless-benchmarks/python-venv/lib/python3.10/site-packages/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "/root/serverless-benchmarks/python-venv/lib/python3.10/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
  File "/root/serverless-benchmarks/python-venv/lib/python3.10/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.NotFound: 404 Client Error for http+docker://localhost/v1.43/containers/19b3cdbf671fd3ccfcf5757018a91c74beb95c47361a17984b6e8829d14f9cb8/exec: Not Found ("No such container: 19b3cdbf671fd3ccfcf5757018a91c74beb95c47361a17984b6e8829d14f9cb8")
```

**System:**
 - SeBS version: 1.1
 - Python version: 3.10.12
 - OS: Ubuntu

**Additional context:**
Later, I was able to successfully create credentials manually and connect to azure.

**Comment by mcopik** [comment]
@nurSaadat Thanks for raising the issue! I'm sorry you're experiencing this problem.

This looks like an issue we had before and was resolved in the development branch. I updated the master branch with the most recent changes. Can you please pull the changes and try again?

**Comment by mcopik** [comment]
@nurSaadat Was your issue resolved?

**Comment by mcopik** [comment]
@nurSaadat Can you please confirm that the issue has been resolved and you can now use Azure credential generator?

**Comment by mcopik** [comment]
@nurSaadat Closing due to inactivity - please let me know if the issue persists and we can help debugging it.
