### ISSUE TITLE
Azure supports only Python 3.7

### ISSUE THREAD

**Issue by nurSaadat** [spcl/serverless-benchmarks#177]
**Describe the bug**
I didn't quite understand what causes the error when running regression tests for azure. I ran regression tests successfully today, both for GCP and for AWS. However there is error in the logs saying that local python version doesn't match 3.7

**To Reproduce**
1. Go to `serverless-benchmarks/`
2. Run the command `./sebs.py benchmark regression test --config config/example.json --deployment azure`
3. Scroll down to see the error

**Expected behavior**
Successful execution of the regression tests, 10/10 passed 

**Logs**
```
sebs.regression.AzureTestSequence.test_311.compression: fail
sebs.regression.AzureTestSequence.test_311.compression: Traceback (most recent call last):
  File "/root/serverless-benchmarks/sebs/regression.py", line 50, in test
    func = deployment_client.get_function(
  File "/root/serverless-benchmarks/sebs/faas/system.py", line 174, in get_function
    function = self.create_function(code_package, func_name)
  File "/root/serverless-benchmarks/sebs/azure/azure.py", line 342, in create_function
    self.update_function(function, code_package)
  File "/root/serverless-benchmarks/sebs/azure/azure.py", line 241, in update_function
    url = self.publish_function(function, code_package, True)
  File "/root/serverless-benchmarks/sebs/azure/azure.py", line 223, in publish_function
    raise e
  File "/root/serverless-benchmarks/sebs/azure/azure.py", line 186, in publish_function
    ret = self.cli_instance.execute(
  File "/root/serverless-benchmarks/sebs/azure/cli.py", line 59, in execute
    raise RuntimeError(
RuntimeError: Command bash -c 'cd /mnt/function && func azure functionapp publish 311-compression-python-3-7-e395acb0 --python --no-build' failed at Azure CLI docker!
 Output Local python version '3.9.2' is different from the version expected for your deployed Function App. This may result in 'ModuleNotFound' errors in Azure Functions. Please create a Python Function App for version 3.9 or change the virtual environment on your local machine to match 'Python|3.7'.
Getting site publishing info...
Skipping build event for functions project (--no-build).
Uploading package...
Uploading 14.7 MB []Upload completed successfully.
Deployment completed successfully.
Syncing triggers...
Syncing triggers...
Syncing triggers...
Syncing triggers...
Syncing triggers...
Syncing triggers...
Error calling sync triggers (BadRequest). Request ID = 'e52541d2-db49-4f8f-943e-f1ee93912c2f'.
```

**System (please complete the following information):**
 - SeBS version: 1.1
 - Python version: 3.10.12
 - OS: Ubuntu

**Comment by mcopik** [comment]
Closing due to inactivity - please feel free to reopen if the issue persists :)
