### ISSUE TITLE
Exception when building azure dependencies

### ISSUE THREAD

**Issue by lbrndnr** [spcl/serverless-benchmarks#96]
I think this can happen for all platforms, but I'm not entirely sure. First this didn't work for debian but now I fiddled around with my own setup and now it stopped working on macOS as well. 

The last time I ran `install.py` was in february and now after reinstalling it stopped working so maybe it has to do with some incompatibility.

```
Traceback (most recent call last):
  File "/Users/Laurin/Documents/ETH/MSc_Thesis/serverless-benchmarks/./sebs.py", line 34, in __call__
    return self.main(*args, **kwargs)
  File "/Users/Laurin/Documents/ETH/MSc_Thesis/serverless-benchmarks/venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/Laurin/Documents/ETH/MSc_Thesis/serverless-benchmarks/venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/Laurin/Documents/ETH/MSc_Thesis/serverless-benchmarks/venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/Laurin/Documents/ETH/MSc_Thesis/serverless-benchmarks/venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/Laurin/Documents/ETH/MSc_Thesis/serverless-benchmarks/venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/Laurin/Documents/ETH/MSc_Thesis/serverless-benchmarks/./sebs.py", line 81, in wrapper
    return func(*args, **kwargs)
  File "/Users/Laurin/Documents/ETH/MSc_Thesis/serverless-benchmarks/./sebs.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/Users/Laurin/Documents/ETH/MSc_Thesis/serverless-benchmarks/./sebs.py", line 520, in experiment_invoke
    experiment.prepare(sebs_client, deployment_client)
  File "/Users/Laurin/Documents/ETH/MSc_Thesis/serverless-benchmarks/sebs/experiments/perf_cost.py", line 59, in prepare
    self._benchmark = deployment_client.get_workflow(self._code_package)
  File "/Users/Laurin/Documents/ETH/MSc_Thesis/serverless-benchmarks/sebs/faas/system.py", line 239, in get_workflow
    rebuilt, _ = code_package.build(self.package_code, True)
  File "/Users/Laurin/Documents/ETH/MSc_Thesis/serverless-benchmarks/sebs/code_package.py", line 511, in build
    self.install_dependencies(self._output_dir)
  File "/Users/Laurin/Documents/ETH/MSc_Thesis/serverless-benchmarks/sebs/code_package.py", line 474, in install_dependencies
    raise e
  File "/Users/Laurin/Documents/ETH/MSc_Thesis/serverless-benchmarks/sebs/code_package.py", line 409, in install_dependencies
    stdout = self._docker_client.containers.run(
  File "/Users/Laurin/Documents/ETH/MSc_Thesis/serverless-benchmarks/venv/lib/python3.9/site-packages/docker/models/containers.py", line 848, in run
    raise ContainerError(
docker.errors.ContainerError: Command 'None' in image 'spcleth/serverless-benchmarks:build.azure.python.3.7' returned non-zero exit status 1: b'useradd: option requires an argument -- \'u\'\nUsage: useradd [options] LOGIN\n       useradd -D\n       useradd -D [options]\n\nOptions:\n  -b, --base-dir BASE_DIR       base directory for the home directory of the\n                                new account\n  -c, --comment COMMENT         GECOS field of the new account\n  -d, --home-dir HOME_DIR       home directory of the new account\n  -D, --defaults                print or change default useradd configuration\n  -e, --expiredate EXPIRE_DATE  expiration date of the new account\n  -f, --inactive INACTIVE       password inactivity period of the new account\n  -g, --gid GROUP               name or ID of the primary group of the new\n                                account\n  -G, --groups GROUPS           list of supplementary groups of the new\n                                account\n  -h, --help                    display this help message and exit\n  -k, --skel SKEL_DIR           use this alternative skeleton directory\n  -K, --key KEY=VALUE           override /etc/login.defs defaults\n  -l, --no-log-init             do not add the user to the lastlog and\n                                faillog databases\n  -m, --create-home             create the user\'s home directory\n  -M, --no-create-home          do not create the user\'s home directory\n  -N, --no-user-group           do not create a group with the same name as\n                                the user\n  -o, --non-unique              allow to create users with duplicate\n                                (non-unique) UID\n  -p, --password PASSWORD       encrypted password of the new account\n  -r, --system                  create a system account\n  -R, --root CHROOT_DIR         directory to chroot into\n  -s, --shell SHELL             login shell of the new account\n  -u, --uid UID                 user ID of the new account\n  -U, --user-group              create a group with the same name as the user\n  -Z, --selinux-user SEUSER     use a specific SEUSER for the SELinux user mapping\n\ngroupmod: option requires an argument -- \'g\'\nUsage: groupmod [options] GROUP\n\nOptions:\n  -g, --gid GID                 change the group ID to GID\n  -h, --help                    display this help message and exit\n  -n, --new-name NEW_GROUP      change the name to NEW_GROUP\n  -o, --non-unique              allow to use a duplicate (non-unique) GID\n  -p, --password PASSWORD       change the password to this (encrypted)\n                                PASSWORD\n  -R, --root CHROOT_DIR         directory to chroot into\n\nerror: failed switching to "/bin/sh": unable to find user /bin/sh: no matching entries in passwd file\n'
```

**Comment by mcopik** [comment]
@lbrndnr Laurin, are you still able to reproduce the issue? I was not able to reproduce it but we have made changes since that point.

Do I understand correctly it occurred on both Debian and MacOS?

**Comment by mcopik** [comment]
Closing down due to inactivity. I can't reproduce the issue.
